# Generated by Django 5.2.1 on 2025-05-21 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentsystem', '0002_department_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='full_name',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('booked_by_admin', models.BooleanField(default=True)),
                ('Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointmentsystem.department')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointmentsystem.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'appointment_date', 'appointment_time')},
            },
        ),
    ]
