# Generated by Django 5.2.1 on 2025-05-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentsystem', '0003_alter_doctor_full_name_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='booked_by_admin',
        ),
    ]
