# Generated by Django 5.2.1 on 2025-05-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentsystem', '0004_remove_appointment_booked_by_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Department',
            new_name='department',
        ),
    ]
