# Generated by Django 5.2.1 on 2025-05-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentsystem', '0006_onlineappointmentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineappointmentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
